use_frameworks!
platform :ios, '10.0'

#target 'AWAREFramework_Example' do
#  pod 'AWAREFramework', :path => '../'
#
#  target 'AWAREFramework_Tests' do
#    inherit! :search_paths
#
#    
#  end
#end

target 'Tests' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-UnitTest' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-DynamicESM' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-SensingApp' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-SimpleClient' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-GoogleLogin' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-Fitbit' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-CustomESM' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-CustomSensor' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-Visualizer' do
  pod 'AWAREFramework', :path => '../'
  pod 'Charts','3.2'
end

target 'AWARE-ScheduleESM' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-ConfigURLESM' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-InteractiveESM' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-AmbientNoise' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-HealthKit' do
  pod 'AWAREFramework', :path => '../'
end

#target 'AWARE-SignificantMotion' do
#  pod 'AWAREFramework', :path => '../'
#end

target 'AWARE-Barometer' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-JSONStorage' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-Conversation' do
  pod 'AWAREFramework', :path => '../'
end
