use_frameworks!
platform :ios, '11.0'

 #target 'AWAREFramework_Example' do
 #  pod 'AWAREFramework', :path => '../'
 #end

 target 'Tests' do
   pod 'AWAREFramework', :path => '../'
 end

 target 'AWARE-UnitTest' do
   pod 'AWAREFramework', :path => '../'
 end

target 'AWARE-DynamicESM' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-SensingApp' do
#  pod 'AWAREFramework/Core', :path => '../'
  pod 'AWAREFramework', :path => '../'
  pod 'AWAREFramework/Microphone', :path => '../'
  pod 'AWAREFramework/MotionActivity', :path => '../'
  pod 'AWAREFramework/Bluetooth', :path => '../'
  pod 'AWAREFramework/Calendar', :path => '../'
  pod 'AWAREFramework/Contact', :path => '../'
  pod 'AWAREFramework/HealthKit', :path => '../'
end

target 'AWARE-SimpleClient' do
  pod 'AWAREFramework', :path => '../'
end


target 'AWARE-Fitbit' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-CustomESM' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-CustomSensor' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-Visualizer' do
  pod 'AWAREFramework', :path => '../'
  pod 'Charts','3.2'
  pod 'AWAREFramework/Microphone', :path => '../'
end

target 'AWARE-ScheduleESM' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-ConfigURLESM' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-InteractiveESM' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-AmbientNoise' do
  pod 'AWAREFramework', :path => '../'
  pod 'AWAREFramework/Microphone', :path => '../'
end

target 'AWARE-HealthKit' do
  pod 'AWAREFramework', :path => '../'
  pod 'AWAREFramework/HealthKit', :path => '../'
end

#target 'AWARE-SignificantMotion' do
#  pod 'AWAREFramework', :path => '../'
#end

target 'AWARE-Barometer' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-JSONStorage' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-Conversation' do
  pod 'AWAREFramework', :path => '../'
  pod 'AWAREFramework/Microphone', :path => '../'
end

target 'AWARE-ForTest' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-SignificantMotion' do
  pod 'AWAREFramework', :path => '../'
end
#
# target 'AWARE-Location' do
#   pod 'AWAREFramework', :path => '../'
# end
#
# target 'AWARE-SimpleClient-ObjC' do
#   pod 'AWAREFramework', :path => '../'
# end
#
# target 'AWARE-StorageTest' do
#   pod 'AWAREFramework', :path => '../'
# end
