use_frameworks!

target 'AWAREFramework_Example' do
  pod 'AWAREFramework', :path => '../'

  target 'AWAREFramework_Tests' do
    inherit! :search_paths

    
  end
end

target 'AWARE-DynamicESM' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-SensingApp' do
  pod 'AWAREFramework', :path => '../'
end

target 'AWARE-SimpleClient' do
  pod 'AWAREFramework', :path => '../'
end
